apiVersion: v1
kind: ConfigMap
metadata:
  name: event-service
  namespace: {{ .Release.Namespace }}
data:
  LOGGING_LEVEL: "INFO"
  MONGO_READ_PREF_NAME: "secondary"
  MONGO_READ_PREF_TAGS: "nodeType=ANALYTICS"
  MONGO_INDEX_MANAGER_MODE: "MANUAL"
  EVEMTS_MONGO_INDEX_MANAGER_MODE: "MANUAL"
  DEPLOY_MODE: "KUBERNETES_ONPREM"
  GOOGLE_APPLICATION_CREDENTIALS: /opt/harness/svc/ceng_gcp_credentials.json
  STACK_DRIVER_LOGGING_ENABLED: "true"
  MEMORY: {{ .Values.java.memory | quote }}
  ce-gcp-home-project-creds: {{ .Values.eventSvcServiceAccounts.ceGCPHomeProjectCreds | quote }}
  MONGO_URI: {{ include "harnesscommon.database.mongo" (dict "database" "harness" "context" $) }}
  EVENTS_MONGO_URI: {{ include "harnesscommon.database.mongo" (dict "database" "events" "context" $) }}